// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ChatPublisher is an autogenerated mock type for the ChatPublisher type
type ChatPublisher struct {
	mock.Mock
}
