// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CommandWriter is an autogenerated mock type for the CommandWriter type
type CommandWriter struct {
	mock.Mock
}
