// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	chat "chat/chat"

	mock "github.com/stretchr/testify/mock"
)

// UserWriter is an autogenerated mock type for the UserWriter type
type UserWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: user
func (_m *UserWriter) Create(user *chat.User) *chat.User {
	ret := _m.Called(user)

	var r0 *chat.User
	if rf, ok := ret.Get(0).(func(*chat.User) *chat.User); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.User)
		}
	}

	return r0
}
