// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	chat "chat/chat"

	mock "github.com/stretchr/testify/mock"
)

// UserManager is an autogenerated mock type for the UserManager type
type UserManager struct {
	mock.Mock
}

// Create provides a mock function with given fields: u
func (_m *UserManager) Create(u *chat.User) *chat.User {
	ret := _m.Called(u)

	var r0 *chat.User
	if rf, ok := ret.Get(0).(func(*chat.User) *chat.User); ok {
		r0 = rf(u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.User)
		}
	}

	return r0
}

// GetByID provides a mock function with given fields: ID
func (_m *UserManager) GetByID(ID string) *chat.User {
	ret := _m.Called(ID)

	var r0 *chat.User
	if rf, ok := ret.Get(0).(func(string) *chat.User); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.User)
		}
	}

	return r0
}
