// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	chat "chat/chat"

	mock "github.com/stretchr/testify/mock"
)

// UserReader is an autogenerated mock type for the UserReader type
type UserReader struct {
	mock.Mock
}

// FinUserByID provides a mock function with given fields: id
func (_m *UserReader) FinUserByID(id string) *chat.User {
	ret := _m.Called(id)

	var r0 *chat.User
	if rf, ok := ret.Get(0).(func(string) *chat.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.User)
		}
	}

	return r0
}
