// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	accounts "chat/accounts"

	mock "github.com/stretchr/testify/mock"
)

// AccountReader is an autogenerated mock type for the AccountReader type
type AccountReader struct {
	mock.Mock
}

// FindByEmail provides a mock function with given fields: email
func (_m *AccountReader) FindByEmail(email string) *accounts.Account {
	ret := _m.Called(email)

	var r0 *accounts.Account
	if rf, ok := ret.Get(0).(func(string) *accounts.Account); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accounts.Account)
		}
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *AccountReader) FindByID(id string) *accounts.Account {
	ret := _m.Called(id)

	var r0 *accounts.Account
	if rf, ok := ret.Get(0).(func(string) *accounts.Account); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accounts.Account)
		}
	}

	return r0
}
