// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	accounts "chat/accounts"

	mock "github.com/stretchr/testify/mock"
)

// TokenManager is an autogenerated mock type for the TokenManager type
type TokenManager struct {
	mock.Mock
}

// Generate provides a mock function with given fields: acc
func (_m *TokenManager) Generate(acc *accounts.Account) (string, error) {
	ret := _m.Called(acc)

	var r0 string
	if rf, ok := ret.Get(0).(func(*accounts.Account) string); ok {
		r0 = rf(acc)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*accounts.Account) error); ok {
		r1 = rf(acc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
