name: Check Peer Review

on:
  push:
    branches:
      - master

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code
        uses: actions/checkout@v1

      - name: coverage
        run: |
          cd backend
          go test ./... -coverprofile=c.out
          go tool cover -html=c.out -o coverage.html
          cat c.out >> coverage.txt
          ls -la

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: unittests
          file: ./backend/coverage.txt
